apiVersion: v1
kind: Pod
metadata:
  name: alpine-pentest
  namespace: kube-system
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "apk update && apk add curl bind-tools --no-cache; sleep 100000"]
  automountServiceAccountToken: true
  hostNetwork: true
  # Убираем serviceAccountName или используем существующий
